Part1
dnsoftware/gophkeeper pull request #1
Opened 2024-06-29 00:10 UTC by dnsoftware

2024-07-04 09:50 UTC, Bazys commented on internal/client/domain/readline.go
> +		pswd2, err = r.ReadPasswordWithConfig(r.passwordCfg)
а как же на ошибки проверять?

2024-07-04 09:56 UTC, Bazys requested changes
чувствуетя что код еще сырой, но общее решение норм. доделывай

2024-07-04 09:56 UTC, Bazys commented on internal/client/domain/client.go
> +	"io/ioutil"
пакет депрекатед

2024-07-04 09:56 UTC, Bazys commented on internal/client/domain/client_base.go
> +					fmt.Println(fmt.Sprintf("[%v] %v", index, val))
так сложно.
а может fmt.Printf

2024-07-04 09:56 UTC, Bazys commented on internal/client/domain/client_base.go
> +					break
а зачем это? в го это лишнее

2024-07-04 09:56 UTC, Bazys commented on internal/client/domain/client.go
> +func usage(w io.Writer) {
зачем эта функция?

2024-07-04 09:56 UTC, Bazys commented on internal/storage/postgresql/entity.go
> +		} else {
зачем else?

2024-07-04 09:56 UTC, Bazys commented on internal/server/handlers/grpc_entity_codes.go
> +func (g *GRPCServer) EntityCodes(ctx context.Context, in *pb.EntityCodesRequest) (*pb.EntityCodesResponse, error) {
неиспользуемые параметры

2024-07-06 11:26 UTC, dnsoftware commented on internal/client/domain/client_base.go
> +					fmt.Println(fmt.Sprintf("[%v] %v", index, val))
Нну да, громоздко. Мне там нужен перевод строки, а у Printf его нет). Исправил везде на fmt.Printf с \n в конце строки.

2024-07-06 11:27 UTC, dnsoftware commented on internal/client/domain/client.go
> +func usage(w io.Writer) {
Она не нужна. Скопировал из примера пакета, убрал уже).

2024-07-06 11:34 UTC, dnsoftware commented on internal/storage/postgresql/entity.go
> +		} else {
Согласен, не нужен)). Убрал везде

2024-07-06 11:37 UTC, dnsoftware commented on internal/client/domain/client_base.go
> +					break
ПХПэшный бэкграунд сказывается видимо)). Машинально поставил!)

2024-07-10 08:12 UTC, merged